// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hthqcgurjxfqgcoqmkzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0aHFjZ3VyanhmcWdjb3Fta3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzNzA3ODAsImV4cCI6MjA2MTk0Njc4MH0.-50k5W_LgKSSFbvAWAbdUKbA2Fj3d3CPZXP4JUfMDOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);